# Generated by Django 4.2.23 on 2025-09-02 08:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyHead',
            fields=[
                ('HeadID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('Birthdate', models.DateField()),
                ('MobileNo', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter exactly 10 digits.', regex='^\\d{10}$')])),
                ('Address', models.TextField()),
                ('State', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Enter exactly 6 digits.', regex='^\\d{6}$')])),
                ('MaritalStatus', models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], max_length=10)),
                ('WeddingDate', models.DateField(blank=True, null=True)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'family_head',
            },
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='fims.familyhead')),
            ],
            options={
                'db_table': 'hobby',
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('MemberID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('Relationship', models.CharField(max_length=50)),
                ('Birthdate', models.DateField()),
                ('MobileNo', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter exactly 10 digits.', regex='^\\d{10}$')])),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('AddressOverride', models.BooleanField(default=False)),
                ('Address', models.TextField(blank=True, null=True)),
                ('State', models.CharField(blank=True, max_length=50, null=True)),
                ('City', models.CharField(blank=True, max_length=50, null=True)),
                ('Pincode', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Enter exactly 6 digits.', regex='^\\d{6}$')])),
                ('is_deleted', models.BooleanField(default=False)),
                ('HeadID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fims.familyhead')),
            ],
            options={
                'db_table': 'family_member',
            },
        ),
    ]
