# Generated by Django 4.2.23 on 2025-09-02 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_hobbies', to='fims.familymember'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_hobbies', to='fims.familyhead'),
        ),
    ]
