# Generated by Django 4.2.23 on 2025-09-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fims', '0002_hobby_member_alter_hobby_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyhead',
            name='Education',
            field=models.CharField(choices=[('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate'), ('Diploma', 'Diploma')], default='Graduate', max_length=20),
        ),
    ]
