# Generated by Django 4.2.23 on 2025-09-03 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fims', '0003_familyhead_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hobby',
            old_name='name',
            new_name='Hobby',
        ),
    ]
