# Generated by Django 4.2.23 on 2025-09-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fims', '0006_passwordreset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyhead',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='city',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (9, 'Soft Deleted')], default=1),
        ),
        migrations.AddField(
            model_name='familyhead',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (9, 'Soft Deleted')], default=1),
        ),
        migrations.AddField(
            model_name='familymember',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (9, 'Soft Deleted')], default=1),
        ),
        migrations.AddField(
            model_name='state',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (9, 'Soft Deleted')], default=1),
        ),
    ]
