# Generated by Django 4.2.23 on 2025-09-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fims', '0007_remove_familyhead_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyhead',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=6),
        ),
        migrations.AddField(
            model_name='familymember',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=6),
            preserve_default=False,
        ),
    ]
