# Generated by Django 4.2.23 on 2025-09-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fims', '0008_familyhead_gender_familymember_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='MaritalStatus',
            field=models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], default='Unmarried', max_length=10),
        ),
    ]
