# Generated by Django 4.2.23 on 2025-09-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fims', '0009_familymember_maritalstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'managed': False},
        ),
    ]
