# Generated by Django 4.2.23 on 2025-09-11 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fims', '0010_alter_city_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.RemoveField(
            model_name='state',
            name='country_id',
        ),
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, to='fims.country'),
            preserve_default=False,
        ),
    ]
