# Generated by Django 4.2.23 on 2025-09-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fims', '0012_adminlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='AddressOverride',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='City',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='Pincode',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='State',
        ),
    ]
