# Generated by Django 4.2.23 on 2025-09-19 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fims', '0013_remove_familymember_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyhead',
            name='MobileNo',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
