# Generated by Django 4.2.23 on 2025-09-19 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fims', '0014_alter_familyhead_mobileno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='member',
        ),
    ]
