# Generated by Django 4.2.23 on 2025-09-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fims', '0015_remove_hobby_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='Education',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='WeddingDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
