# Generated by Django 4.2.23 on 2025-09-29 09:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fims', '0016_familymember_education_familymember_weddingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyhead',
            name='HeadID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
