# Generated by Django 4.2.23 on 2025-09-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fims', '0017_alter_familyhead_headid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyhead',
            name='HeadID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
